import React, { Fragment } from 'react';

const About = () => {
    return (
        <Fragment>
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus itaque at repellat provident officiis omnis animi! Vel consequuntur ipsa recusandae magni, in enim cumque nemo reprehenderit. Facere officia aliquam voluptates vero accusantium nemo quasi ab veritatis id qui aut exercitationem labore in dolores nostrum accusamus et maiores, ducimus neque, corporis sit nam excepturi doloremque? Reiciendis culpa, nostrum illo quae nemo quis suscipit inventore porro accusantium explicabo similique nihil adipisci asperiores quos quidem quam, alias autem modi laborum! Reprehenderit soluta dolor, nulla, necessitatibus ullam animi eos provident, temporibus possimus dignissimos labore magnam omnis quasi molestiae autem dicta. Illo sed minus, iusto, veniam placeat fuga veritatis facere fugiat qui facilis laborum hic dolore iste in? Minima voluptas labore vitae quasi rerum exercitationem facilis neque perspiciatis ducimus totam, aspernatur accusantium temporibus aliquam porro autem nobis quia unde aut molestias dolorem praesentium. Eum quis cupiditate dignissimos assumenda recusandae obcaecati debitis, maiores rem doloremque nisi exercitationem ea atque. Iste, earum! Iusto, officia assumenda? Cupiditate ratione magni nemo libero voluptate natus, ipsam facere quasi? Debitis, nostrum quod voluptatibus sunt odit eos natus labore perferendis repudiandae pariatur omnis quisquam commodi dignissimos minus voluptas. Doloremque magnam eveniet ab ea at veniam fugit, possimus minima et dolor ullam fugiat maxime ex eum ducimus eius perspiciatis officia culpa exercitationem provident autem, porro officiis cumque? Ipsum fugit non harum! Iure nam cum, modi dolorem voluptatem nisi? Est soluta esse voluptatum inventore nemo dolore, libero, asperiores, quaerat nisi qui similique cum dolores omnis? Saepe dignissimos, rem sed iusto id molestias non omnis rerum libero! Ipsum accusantium ullam totam voluptatum porro laudantium sed dignissimos cum doloremque sint. Ex voluptate velit quo, quibusdam cupiditate ipsa ut illum quaerat dicta excepturi inventore ad modi dolor soluta maxime voluptas sint at. Cum temporibus totam omnis eveniet hic assumenda nostrum ab deleniti tempore corrupti? Atque, ipsa?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aspernatur consequatur praesentium neque itaque, cumque unde commodi reiciendis fugiat. Quos, laboriosam corrupti eos quae tempore corporis nulla ut, unde sapiente nisi esse sunt hic assumenda facere cum nihil. Delectus cumque laboriosam voluptatum animi earum sapiente modi iure suscipit! Perspiciatis quos accusantium accusamus, a ut quidem harum quod reiciendis consectetur nisi et dignissimos alias optio doloribus expedita modi. Quis doloremque, dicta, voluptas incidunt eaque et quas, nisi qui deserunt provident enim possimus laudantium eos voluptatum velit? Similique alias consequatur qui dolorum! Eaque temporibus beatae natus eos repellendus architecto amet corrupti tempore minus!</p>
        </Fragment>
        
    )
}

export default About;